apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"webapp"},"name":"webapp-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"webapp"}},"template":{"metadata":{"labels":{"app":"webapp"}},"spec":{"containers":[{"env":[{"name":"USER_NAME","valueFrom":{"secretKeyRef":{"key":"mongo-user","name":"mongo-secret"}}},{"name":"USER_PWD","valueFrom":{"secretKeyRef":{"key":"mongo-password","name":"mongo-secret"}}},{"name":"DB_URL","valueFrom":{"configMapKeyRef":{"key":"mongo-url","name":"mongo-config"}}}],"image":"nanajanashia/k8s-demo-app:v1.0","name":"webapp","ports":[{"containerPort":3000}]}]}}}}
  creationTimestamp: "2022-05-30T05:07:40Z"
  generation: 1
  labels:
    app: webapp
  name: webapp-deployment
  namespace: default
  resourceVersion: "6830"
  uid: 6dd2c8a8-d567-4b18-a77d-8ddcad628714
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
    spec:
      containers:
      - env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              key: mongo-user
              name: mongo-secret
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              key: mongo-password
              name: mongo-secret
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              key: mongo-url
              name: mongo-config
        image: nanajanashia/k8s-demo-app:v1.0
        imagePullPolicy: IfNotPresent
        name: webapp
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-05-30T05:08:39Z"
    lastUpdateTime: "2022-05-30T05:08:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-05-30T05:07:40Z"
    lastUpdateTime: "2022-05-30T05:08:39Z"
    message: ReplicaSet "webapp-deployment-56dbf5d695" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
